### ISSUE TITLE
typo GetMapping in controller

### ISSUE THREAD

**Issue by zlssy** [thinkkoa/koatty_demo#2]
import { Controller, BaseController, GetMaping, PathVariable, RequestBody } from "koatty";
import { App } from '../App';

@Controller()
export class IndexController extends BaseController {
    app: App;

    /**
     * Custom constructor
     *
     */
    init() {
        //...
    }

    @GetMapping("/")
    index(@PathVariable("path") path: string) {
        return this.ok('Hello, Koatty!');
    }
}

**Comment by richenlin** [comment]
Sorry, this is a low level spelling mistake. We will fix

**Comment by richenlin** [comment]
fixed
